export const PROJECTS = [
    {
      id: '01',
      name: 'Emotion-Aware Task Scheduling System',
      tagline: 'ML-driven system for habit and emotion-based task planning',
      desc: 'Syracuse University (Jun 2025–Mar 2026, Prof. Nadeem Ghani). Built on 14,584 task records, 10 personas, 365 days, 16 features. Used Logistic Regression, Decision Tree (best F1: 0.697), Random Forest, XGBoost. SHAP analysis confirmed Mood Score as dominant predictor (SHAP: 0.749). TextBlob (MAE: 0.48) outperformed VADER (MAE: 0.54).',
      stack: [
        { label: 'Python', color: 'indigo' },
        { label: 'scikit-learn', color: 'sky' },
        { label: 'XGBoost', color: 'emerald' },
        { label: 'SHAP', color: 'rose' },
        { label: 'TextBlob', color: 'amber' },
        { label: 'VADER', color: 'amber' },
      ],
      github: 'https://github.com/prerna1001/Research_Assistant',
      live: null,
    },
    {
      id: '02',
      name: 'AIoT-Based Smart Education System',
      tagline: 'Dual-layer authentication & context-aware tutoring for smart classrooms',
      desc: 'Co-authored with Adithya Neelakantan, Pratik Satpute, Prerna Shinde, Tejas Manjunatha Devang (equal contribution). Syracuse University, College of Engineering and Computer Science. Published on arXiv, October 2025 (arXiv:2510.26999). Integrated AI and IoT platform for smart classrooms: dual-layer attendance authentication, context-aware RAG-based tutoring chatbot, automated quiz generation, and IoT environmental monitoring.',
      stack: [
        { label: 'RAG-based LLMs', color: 'indigo' },
        { label: 'LangChain', color: 'sky' },
        { label: 'FAISS', color: 'emerald' },
        { label: 'OpenAI Embeddings', color: 'rose' },
        { label: 'Google Gemini', color: 'amber' },
        { label: 'ESP32', color: 'indigo' },
        { label: 'RFID', color: 'sky' },
        { label: 'WiFi', color: 'emerald' },
        { label: 'Streamlit', color: 'rose' },
      ],
      github: null,
      live: null,
      arxiv: 'https://arxiv.org/abs/2510.26999',
      arxivLabel: 'arXiv Paper',
    },
  {
    id: '03',
    name: 'Vanessa — Voice AI Acquisitions Assistant',
    tagline: 'Auto-calls homeowners, classifies leads, and surfaces results in a live React dashboard',
    desc: 'Vanessa auto-calls homeowners using Vapi.ai, gathers selling intent through a structured conversation, summarizes each call with OpenAI GPT, and classifies leads as Qualified or Unqualified. Supports Excel uploads of phone number lists for bulk sequential outbound calling. Results display in a real-time React dashboard with lead tracking and call progress visibility.',
    stack: [
      { label: 'Node.js', color: 'emerald' },
      { label: 'Express', color: 'emerald' },
      { label: 'Vapi.ai', color: 'indigo' },
      { label: 'OpenAI GPT', color: 'sky' },
      { label: 'React', color: 'indigo' },
      { label: 'Tailwind', color: 'sky' },
    ],
    github: 'https://github.com/prerna1001/Venessa_Project',
    live: null,
  },
  {
    id: '04',
    name: 'PlanPal — AI Planning Assistant',
    tagline: 'Voice-enabled AI assistant for travel, reminders & task planning on Cloudflare',
    desc: 'Built with Cloudflare Agents, Durable Objects, and Workers AI. PlanPal handles trip planning, event scheduling, and smart reminders through a chat or voice interface. Conversation history persists across sessions via Cloudflare Agents\' built-in state management. Reminders are stored in Durable Objects with alarm-based scheduling, and the LLM (LLaMA 3) runs on Workers AI infrastructure.',
    stack: [
      { label: 'TypeScript', color: 'sky' },
      { label: 'React', color: 'indigo' },
      { label: 'Cloudflare Workers', color: 'amber' },
      { label: 'Durable Objects', color: 'rose' },
      { label: 'Workers AI / LLaMA 3', color: 'indigo' },
    ],
    github: 'https://github.com/prerna1001/cf_ai_planpal',
    live: 'https://7bed3bf5.cf-ai-planpal.pages.dev/',
  },
  {
    id: '05',
    name: 'Universal URL Research Tool',
    tagline: 'RAG-powered research assistant that answers questions from any URL',
    desc: 'A Retrieval-Augmented Generation (RAG) system that fetches URLs, chunks and embeds content into PostgreSQL with pgvector, and answers natural language questions grounded only in those sources. Uses LangChain for orchestration, sentence-transformers for embeddings, and a Cloudflare Worker exposing LLaMA 3 as the LLM. Deployed live on Streamlit Cloud with Supabase PostgreSQL.',
    stack: [
      { label: 'Python', color: 'indigo' },
      { label: 'LangChain', color: 'sky' },
      { label: 'PostgreSQL + pgvector', color: 'rose' },
      { label: 'Streamlit', color: 'emerald' },
      { label: 'Cloudflare Workers AI', color: 'amber' },
      { label: 'RAG', color: 'indigo' },
    ],
    github: 'https://github.com/prerna1001/universal-url-researc',
    live: 'https://universal-url-researc-7jj88zvtofjkvegmykp447.streamlit.app/',
  },
  {
    id: '06',
    name: 'Pharma Press Release Search Platform',
    tagline: 'Full-stack intelligence platform for pharmaceutical newsroom content',
    desc: 'Built for a hackathon — scrapes press releases from AstraZeneca, J&J, Merck, Novo Nordisk, and Pfizer, indexes them in Elasticsearch, and serves a React frontend with advanced search, filtering, highlighted snippets, and CSV export. FastAPI backend exposes paginated endpoints for search, filter config, and full-text detail retrieval. Fully containerized with Docker Compose.',
    stack: [
      { label: 'React', color: 'indigo' },
      { label: 'FastAPI', color: 'sky' },
      { label: 'Python', color: 'rose' },
      { label: 'Elasticsearch', color: 'emerald' },
      { label: 'Docker', color: 'amber' },
      { label: 'BeautifulSoup', color: 'indigo' },
    ],
    github: 'https://github.com/prerna1001/prerna_hackathin',
    live: null,
  },
  {
    id: '07',
    name: 'Automated Email Reminder Platform',
    tagline: 'Full-stack scheduling platform for recurring automated emails',
    desc: 'Users schedule daily, weekly, monthly, or custom follow-up emails. Spring Boot backend stores schedules in Firebase Firestore, and a Java scheduler triggers emails via Twilio SendGrid at exact configured times. React frontend provides full task management — create, view, edit, and delete automations. Deployed on Vercel with Docker containerization.',
    stack: [
      { label: 'Java 21', color: 'amber' },
      { label: 'Spring Boot', color: 'rose' },
      { label: 'React.js', color: 'indigo' },
      { label: 'Firebase Firestore', color: 'sky' },
      { label: 'Twilio SendGrid', color: 'emerald' },
      { label: 'Docker', color: 'indigo' },
    ],
    github: 'https://github.com/prerna1001/task-automation',
    live: 'https://task-automation-ten.vercel.app',
  },
  {
    id: '08',
    name: 'Safe Python Executor',
    tagline: 'Secure sandboxed execution environment for untrusted Python code',
    desc: 'A production-ready Flask REST API for safely executing arbitrary user-submitted Python scripts using nsjail for Linux namespace-based process isolation. Enforces strict syscall whitelisting, resource limits (512MB RAM, 10s timeout, no network access), and read-only filesystem mounts. Deployed on Google Cloud Run. Reduced first-time success rate from 40% to 85% through comprehensive error handling.',
    stack: [
      { label: 'Python', color: 'indigo' },
      { label: 'Flask', color: 'sky' },
      { label: 'nsjail', color: 'rose' },
      { label: 'Docker', color: 'amber' },
      { label: 'Google Cloud Run', color: 'emerald' },
    ],
    github: 'https://github.com/prerna1001/safe-python-executor',
    live: null,
  },
  {
    id: '09',
    name: 'Real-Time Updates System',
    tagline: 'Real-time data synchronization and update streaming',
    desc: 'A real-time updates system built to stream and synchronize data across clients. Implements efficient event-driven architecture for pushing live updates to connected users.',
    stack: [
      { label: 'JavaScript', color: 'amber' },
      { label: 'Node.js', color: 'emerald' },
      { label: 'React', color: 'indigo' },
    ],
    github: 'https://github.com/prerna1001/Real_Time_Updates',
    live: null,
    note: 'Repo may be private',
  },
]

export const EXPERIENCE = [
  {
    company: 'Syracuse University — College of Engineering & Computer Science',
    role: 'Research Assistant',
    period: 'Jun 2025 – Present · 10 months',
    location: 'Remote · Syracuse, NY',
    type: 'current',
    stack: ['Python', 'scikit-learn', 'XGBoost', 'LSTM', 'SHAP', 'BERT', 'VADER', 'TextBlob'],
    highlights: [
      'Building emotion-aware ML models to predict task adherence using behavioral, temporal, and mood-based features across a dataset of 14,584 records spanning 10 user personas and 365 days.',
      'Designing synthetic datasets and user personas simulating multi-week task routines and emotional patterns for controlled experimentation.',
      'Training and evaluating Logistic Regression, Decision Trees (best F1: 0.697), Random Forests, XGBoost, and LSTM models to assess prediction accuracy and generalization.',
      'Applying feature engineering — lag features, rolling averages, interaction terms (Mood x Priority) — and using SHAP for model interpretability; confirmed Mood Score as dominant predictor (SHAP value: 0.749).',
      'Evaluating sentiment analysis tools (TextBlob MAE: 0.48 vs VADER MAE: 0.54) and implementing Q-learning adaptive recommendation policy for personalized scheduling.',
      'Published full end-to-end reproducible pipeline on GitHub: github.com/prerna1001/Research_Assistant',
    ],
  },
  {
    company: 'D&D Motor Systems Inc.',
    role: 'Software Engineer Intern',
    period: 'Jan 2025 – May 2025 · 5 months',
    location: 'On-site · Syracuse, NY',
    type: 'past',
    stack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'Bootstrap', 'jQuery', 'Figma', 'SQL', 'phpMyAdmin'],
    highlights: [
      'Designed and prototyped responsive web layouts using Figma, HTML Canvas, Bootstrap, and jQuery, incorporating stakeholder feedback before implementation.',
      'Redesigned 20+ legacy web pages into mobile-friendly, WCAG-accessible interfaces, improving usability across devices.',
      'Contributed to a website refresh that improved SEO performance ~70% and increased user engagement by 13% through refined layouts and analytics-guided decisions.',
      'Developed and integrated frontend and backend functionality using HTML, CSS, JavaScript, PHP, Bootstrap, and jQuery for POS-related features.',
      'Integrated Apryse Document Viewer to enable in-browser previews of product manuals and datasheets with optional downloads.',
      'Maintained and optimized a database of 6,000+ motor/controller records using SQL through phpMyAdmin, reducing load times and streamlining navigation.',
    ],
  },
  {
    company: 'iConsult Collaborative at Syracuse University',
    role: 'Software Engineer',
    period: 'Oct 2024 – May 2025 · 8 months',
    location: 'Remote · Syracuse, NY',
    type: 'past',
    stack: ['React.js', 'Next.js', 'TypeScript', 'Node.js', 'Python', 'AWS EC2', 'PostgreSQL', 'Java', 'JavaScript'],
    projects: [
      {
        name: 'Healthcare Ticketing & Service Request Platform',
        points: [
          'Built a ticketing platform enabling clinicians and staff to submit IT issues and track, prioritize, and resolve requests through structured workflows.',
          'Designed and implemented backend REST APIs for ticket creation, updates, and status management — deployed on AWS EC2 with secure data storage and access controls.',
          'Developed React dashboards to view support tickets, filter by urgency or department, and monitor progress, reducing manual follow-ups and improving turnaround time.',
          'Contributed to secure API design, role-based access for staff vs IT personnel, automated testing, and code reviews to ensure backend reliability.',
        ],
      },
      {
        name: 'Voice-Enabled AI Patient Follow-up Agent',
        points: [
          'Built a voice-enabled AI follow-up agent for post-visit patient check-ins using speech recognition and transcript parsing to capture patient intent and outcomes.',
          'Implemented backend services and REST APIs to orchestrate call flows and manage dynamic question logic.',
          'Developed a React + TypeScript dashboard to review call status, transcripts, and outcomes, enabling faster clinical review.',
          'Designed an AI-powered information extraction pipeline to structure transcript data, reducing manual review effort by 30–35%.',
        ],
      },
      {
        name: 'Traffic Monitoring System',
        points: [
          'Built interactive WCAG-compliant dashboards to visualize real-time operational data with responsive user interfaces.',
          'Collaborated with designers using Figma to implement accurate, accessible UI patterns.',
          'Integrated frontend views with backend APIs across the full UI lifecycle — component architecture, state management, performance tuning, and accessibility improvements.',
        ],
      },
    ],
  },
  {
    company: 'Quantum Data Engines India Pvt. Ltd.',
    role: 'Software Engineer',
    period: 'Jun 2022 – May 2023 · 1 year',
    location: 'On-site · Mumbai, India',
    type: 'past',
    stack: ['Java', 'Spring Boot', 'React.js', 'Oracle SQL', 'MS SQL', 'Apache POI', 'REST APIs', 'Postman', 'Agile'],
    highlights: [
      'Built backend services using Java + Spring Boot and responsive React.js UIs for AML and compliance client applications, integrating RESTful APIs.',
      'Optimized complex Oracle SQL and MS SQL queries and stored procedures for scalability and reliable data processing.',
      'Contributed to AML workflow enhancements — resolving input handling issues, improving data storage/rendering logic, and enabling reliable case tracking.',
      'Implemented bulk processing functionality for AML workflows via structured file uploads, significantly reducing manual operational effort.',
      'Developed document generation features using Apache POI for structured regulatory compliance reports in Word format from backend data.',
      'Improved application security with server-side and UI-level protections against common web vulnerabilities.',
      'Assisted with migration and testing as legacy components were refactored toward a modular, service-oriented architecture.',
    ],
  },
]

export const SKILLS = [
  {
    group: 'Languages',
    sub: 'Core programming languages',
    color: 'indigo',
    items: ['Python', 'Java', 'JavaScript (ES6+)', 'TypeScript', 'SQL', 'PHP', 'HTML5', 'CSS3', 'Bash'],
  },
  {
    group: 'Frontend',
    sub: 'UI, components & design',
    color: 'sky',
    items: ['React', 'Next.js', 'Angular', 'Streamlit', 'Tailwind CSS', 'Bootstrap', 'jQuery', 'Figma', 'Adobe Creative Cloud'],
  },
  {
    group: 'Backend & APIs',
    sub: 'Services, APIs & architecture',
    color: 'rose',
    items: ['FastAPI', 'Flask', 'Spring Boot', 'Node.js', 'Express', 'REST APIs', 'ConnectRPC', 'Hibernate', 'JSP', 'Maven', 'Gradle'],
  },
  {
    group: 'AI / ML & Agents',
    sub: 'Models, pipelines & intelligence',
    color: 'emerald',
    items: ['LangChain', 'RAG', 'LLM evaluation', 'LLMs Integration', 'OpenAI API', 'LLaMA 3', 'Cloudflare Workers AI', 'Vapi.ai', 'ASR', 'Multi-turn conversation design', 'SHAP', 'XGBoost', 'LSTM', 'BERT', 'VADER', 'TextBlob', 'Pandas', 'NumPy'],
  },
  {
    group: 'Databases',
    sub: 'Storage & data systems',
    color: 'amber',
    items: ['PostgreSQL', 'pgvector', 'Supabase', 'MySQL', 'Oracle SQL', 'MS SQL', 'Firebase / Firestore', 'NoSQL'],
  },
  {
    group: 'Cloud & DevOps',
    sub: 'Infrastructure & deployment',
    color: 'indigo',
    items: ['AWS (EC2, S3)', 'Docker', 'Vercel', 'Google Cloud Run', 'Cloudflare Workers', 'Cloudflare Pages', 'Durable Objects', 'Linux', 'Git', 'GitHub', 'Jira', 'Agile (Scrum)'],
  },
  {
    group: 'Tools & Testing',
    sub: 'Dev tools & practices',
    color: 'sky',
    items: ['Postman', 'Playwright', 'Jest', 'React Testing Library', 'JUnit', 'IntelliJ IDEA', 'VS Code', 'Eclipse', 'Chrome DevTools', 'Elasticsearch', 'Tableau', 'Apache POI', 'Apryse Document Viewer'],
  },
]

export const EDUCATION = [
  {
    uni: 'Syracuse University',
    degree: 'Master of Science',
    field: 'Computer Science — College of Engineering & Computer Science',
    period: 'Aug 2023 – May 2025',
    grade: 'GPA: 3.677 / 4.0',
    tags: [
      'Structured Programming & Formal Methods',
      'Computer Architecture',
      'Intro to Database Management',
      'Social Media & Data Mining',
      'Design & Analysis of Algorithms',
      'Object Oriented Design',
      'Applied Natural Language Processing',
      'Introduction to Cryptography',
      'Principles of Operating Systems',
      'Internet of Things: App Dev',
    ],
    status: 'completed',
  },
  {
    uni: 'Mumbai University',
    degree: 'Bachelor of Science',
    field: 'Information Technology',
    period: '2019 – 2022',
    grade: 'CGPA: 8.24 / 10',
    tags: ['Java', 'Web Development', 'Databases', 'Data Structures'],
    status: 'completed',
  },
]
